WebApplication4/Controllers/Modules1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassLibrary1;
using WebApplication4.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNet.Identity;
using Microsoft.Exchange.WebServices.Data;

namespace WebApplication4.Controllers
{
    public class Modules1Controller : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<IdentityUser> _userManager;

        public Modules1Controller(ApplicationDbContext context, Microsoft.AspNetCore.Identity.UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Modules1
        public async Task<IActionResult> Index()
        {
            //Get current users list of modules
            var currentUser = await _userManager.GetUserAsync(User);

            if(currentUser != null)
            {
                //Filter modules
                var Table1 = await _context.Table1.Where(t => t.UserId == currentUser.Id).ToListAsync();
                return View(Table1);
            }
            else
            {
                return NotFound(); // Or handle accordingly if user not found
            }
        }

        // GET: Table1/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Table1 == null)
            {
                return NotFound();
            }

            var table1 = await _context.Table1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (table1 == null)
            {
                return NotFound();
            }

            return View(table1);
        }


        // GET: Modules1/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Modules1/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Code,Credits,ClassHoursPerWeek,StartDate,NumOfWeeks,HoursWorked,EndDate")] Table1 table1)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _userManager.GetUserAsync(User);

                if (currentUser != null)
                {
                    table1.UserId= currentUser.Id; //Set UserId to currently signed-in user's Id

                    _context.Add(table1);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                }
                
            }
            return View(table1);
        }

        // GET: Table1/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Table1 == null)
            {
                return NotFound();
            }

            var table1 = await _context.Table1.FindAsync(id);
            if (table1 == null)
            {
                return NotFound();
            }
            return View(table1);
        }

        // POST: Table1/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Code,Credits,ClassHoursPerWeek,StartDate,NumOfWeeks,HoursWorked,EndDate,SelfStudyHours,RemainingHours,UserId")] Table1 table1)
        {
            if (id != table1.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(table1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Table1Exists(table1.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(table1);
        }

        // GET: Table1/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Table1 == null)
            {
                return NotFound();
            }

            var table1 = await _context.Table1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (table1 == null)
            {
                return NotFound();
            }

            return View(table1);
        }

        // POST: Table1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Table1 == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Table1'  is null.");
            }
            var table1 = await _context.Table1.FindAsync(id);
            if (table1 != null)
            {
                _context.Table1.Remove(table1);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        private bool Table1Exists(int id)
        {
            return (_context.Table1?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication4/Controllers/SelfStudyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ClassLibrary1;
using WebApplication4.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using NPOI.SS.Formula.Functions;
using System.Reflection;
using System.Globalization;

namespace WebApplication4.Controllers
{
    public class SelfStudyController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<IdentityUser> _userManager;

        public SelfStudyController(ApplicationDbContext context, Microsoft.AspNetCore.Identity.UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: SelfStudy
        public async Task<IActionResult> Index() { 
            //Get current users list of modules
            var currentUser = await _userManager.GetUserAsync(User);

            if (currentUser != null)
            {
                //Filter modules
                var Table1 = await _context.Table1.Where(t => t.UserId == currentUser.Id).ToListAsync();
                return View(Table1);
            }
            else
            {
                return NotFound(); // Or handle accordingly if user not found

            }
        }

        public IActionResult CalculateSelfStudyHours()
        {
            //Retrieve information from database Table1
            Table1 t = _context.Table1.FirstOrDefault();

            //Convert string properties to integers
            int Credits = int.Parse(t.Credits.ToString());
            int NumOfWeeks = int.Parse(t.NumOfWeeks.ToString());
            int ClassHoursPerWeek = int.Parse(t.ClassHoursPerWeek.ToString());

            int selfStudyHoursPerWeek = (Credits * 10) / NumOfWeeks - ClassHoursPerWeek;
            ViewBag.SelfStudyHours = selfStudyHoursPerWeek.ToString();
            return View();
        }
        // GET: SelfStudy/Create
        public IActionResult Create()
        {
            return View();
        }
       
        // POST: SelfStudy/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Code,NumOfWeeks,Credits")] Table1 table1)
        {
            if (ModelState.IsValid)
            {
                var currentUser = await _userManager.GetUserAsync(User);

                if (currentUser != null)
                {
                    table1.UserId = currentUser.Id; //Set UserId to currently signed-in user's Id

                    _context.Add(table1);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));

                }
            }
            
            return View(table1);
        }
       

        // GET: SelfStudy/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Table1 == null)
            {
                return NotFound();
            }

            var table1 = await _context.Table1.FindAsync(id);
            if (table1 == null)
            {
                return NotFound();
            }
            return View(table1);
        }

        // POST: SelfStudy/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,NumOfWeeks")] Table1 table1)
        {
            if (id != table1.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(table1);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Table1Exists(table1.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(table1);
        }

        // GET: SelfStudy/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Table1 == null)
            {
                return NotFound();
            }

            var table1 = await _context.Table1
                .FirstOrDefaultAsync(m => m.Id == id);
            if (table1 == null)
            {
                return NotFound();
            }

            return View(table1);
        }

        // POST: SelfStudy/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Table1 == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Table1'  is null.");
            }
            var table1 = await _context.Table1.FindAsync(id);
            if (table1 != null)
            {
                _context.Table1.Remove(table1);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Table1Exists(int id)
        {
          return (_context.Table1?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApplication4/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudyBuddy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication4.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication4</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Modules1" asp-action="Index">Modules</a>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SelfStudy" asp-action="Index">Number of Self-Study Hours</a>
                            </li>
                        }
                         @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="RemainingHours" asp-action="Index">Number of Self Remaining Hours</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StudyBuddy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>